# Generated by Django 5.0.4 on 2024-04-25 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufactured_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 25, 1, 8, 55, 845188, tzinfo=datetime.timezone.utc), verbose_name='Дата производства продукта'),
        ),
    ]
